spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarydb  # Replace 'librarydb' with your database name
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Admin  # Replace with your MySQL username
    password: 123456  # Replace with your MySQL password
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create or update tables
    show-sql: true  # Print SQL queries in the console
